[package]
name = "logout-other-users"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
check_elevation = "0.2.4"
windows = { version = "0.60", features = [
    "Win32_Foundation",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
] }

[build-dependencies]
winres = "0.1"